Improve Raspberry Pi support.
f-secure-foundry/tamago pull request #6
Opened 2020-09-15 08:38 UTC by abarisani

This PR improves raspberry pi support by:

  * making the code more consistent with the rest of the codebase
  * making the pi specific packages more consistent among themselves
  * removing unused functions or duplicate constants
  * adding missing documentation
  * fixing broken linkx
  * adding required copyright and licensing notes

2020-09-17 08:32 UTC, abarisani commented
@kenbell can you take a look?

2020-09-18 06:41 UTC, kenbell commented
@abarisani - sure.  I didn't get a chance today.  I'll take a look over at the weekend.

2020-09-21 00:52 UTC, kenbell requested changes
The RNG code needs a couple of fixes to allow tamago to startup.  I've added comments with suggested fixes.

I have added a couple of notes for stylistic / naming stuff.

There's also a latent bug in the code i contributed that could do with being fixed.

2020-09-21 00:52 UTC, kenbell commented on soc/bcm2835/rng.go
> +	RNG_CTRL = 0x0
`RNG_CTRL` is a register, should be `RNG_BASE + 0x0`

```suggestion
	RNG_CTRL = RNG_BASE + 0x0
```

2020-09-21 00:52 UTC, kenbell commented on soc/bcm2835/timer.go
> +const WatchdogFreq = uint64(16 * time.Microsecond)
Comment and name mis-match.  This is technically a period, not a frequency.

2020-09-21 00:52 UTC, kenbell commented on soc/bcm2835/gpio.go
> +	reg.Write(GPPUD, 0)
Looks like this was a bug in the code I submitted - needs to be offset by PeripheralAddress
```suggestion
	reg.Write(PeripheralAddress(GPPUD), 0)
```

2020-09-21 00:52 UTC, kenbell commented on soc/bcm2835/gpio.go
> +func (gpio *GPIO) SelectFunction(n uint32) (err error) {
This method is possibly going to be confusing.   `SelectionFunction(FPIO_FN5) == SelectionFunction(2)`.  I added type to force callers to understand this isn't a simple 1-to-n thing, but is actually specific values.  Can we use a type, rather than uint32?

2020-09-21 00:52 UTC, kenbell commented on soc/bcm2835/rng.go
> +	reg.Set(hw.ctrl, CTRL_EN)
`reg.Set` fails to correctly initialize the hardware - the register should be set to `0x1`, not have the first bit set it appears.  With reg.Set, tamago fails to initialize getting stuck in the loop waiting for random bytes to be available.
```suggestion
	reg.Write(hw.ctrl, CTRL_EN)
```

2020-09-21 08:27 UTC, abarisani commented on soc/bcm2835/timer.go
> +const WatchdogFreq = uint64(16 * time.Microsecond)
Fixed in https://github.com/f-secure-foundry/tamago/pull/6/commits/86bf59abca3aab106a982c7041d59f7a1a17e175

2020-09-21 09:01 UTC, abarisani commented on soc/bcm2835/gpio.go
> +func (gpio *GPIO) SelectFunction(n uint32) (err error) {
Ok sorry, I didn't like the overloading (especially in constants definition) that this resulted in. It made everything harder to read, can you please check if [this](https://github.com/f-secure-foundry/tamago/pull/6/commits/d6f81c9234877f539396d7dc178ae5d23b50de05) is sufficient or if there are more concerns?

2020-09-21 14:47 UTC, kenbell commented on soc/bcm2835/gpio.go
> +func (gpio *GPIO) SelectFunction(n uint32) (err error) {
Thanks - that looks good.

2020-09-21 14:59 UTC, kenbell commented
Thanks for updates.  Pi2 seems to be working fine.  PiZero I'm seeing corrupt output on the UART - I'll take a look.

2020-09-21 18:10 UTC, abarisani commented
> Thanks for updates. Pi2 seems to be working fine. PiZero I'm seeing corrupt output on the UART - I'll take a look.

Ok, I'll wait for the update on the PiZero before merging then. Thanks!

2020-09-22 04:10 UTC, kenbell approved these changes
PiZero issue was due to a change on my end - i was missing setting in config.txt on my test system.  Needed to add `core_freq=250` to the Pi config.txt (https://www.raspberrypi.org/documentation/configuration/uart.md)

2020-09-22 07:42 UTC, merged